add composer options

diff --git a/bin/docker-create-project b/bin/docker-create-project
--- a/bin/docker-create-project
+++ b/bin/docker-create-project
@@ -190,8 +190,9 @@ else
         symfony )   package="symfony/website-skeleton"
                     [[ -z "${options[@]}" ]] && options=("--prefer-dist")
                     ;;
-        * )         usage
-                    exit
+        * )         echo "Error: Application not found."
+                    usage
+                    exit 1
                     ;;
     esac
 fi
