create permanent self-signed certificate

diff --git a/install b/install
--- a/install
+++ b/install
@@ -2,6 +2,39 @@
 
 cd "$(dirname "$0")"
 
+if [[ ! -f traefik/dynamic.toml ]]; then
+    cp traefik/dynamic-sample.toml traefik/dynamic.toml
+
+    echo "Created traefik/dynamic.toml file."
+
+    cert_filename="traefik"
+
+    if [[ "$1" = "--cert-filename" ]]; then
+        if [[ -n "$2" ]]; then
+            cert_filename="$2"
+        else
+            echo "Error: SSL certificate file name is required."
+            exit 1
+        fi
+    fi
+
+    if [[ -f "traefik/cert/${cert_filename}.key" ]]; then
+        echo "SSL certificate already exists."
+    else
+        traefik/create-cert --cert-filename "${cert_filename}"
+
+        if [[ "${cert_filename}" != "traefik" ]]; then
+            sed -i.bak "s/traefik.crt/${cert_filename}.crt/g" "traefik/dynamic.toml"
+            sed -i.bak "s/traefik.key/${cert_filename}.key/g" "traefik/dynamic.toml"
+            rm "traefik/dynamic.toml.bak"
+        fi
+
+        echo "Created SSL certificate."
+    fi
+else
+    echo "Traefik dynamic configuration file already exists."
+fi
+
 if [[ ! -f services ]]; then
     cp services-sample services
     echo "Created services file."
